### ISSUE TITLE
pds-tools as a pip-installable package

### ISSUE THREAD

**Issue by giuseppetotaro** [SETI/rms-tools#5]
Hello,

I am using `pds-tools` as an external module for my Python code. Currently, I copied your source code within my project and then addedd a `__init__.py` file into `pds-tools` sub-folder in order to import `vicar`from `pds-tools` as follows:

> from pdstools import vicar

However, it would be much better to have `pds-tools` as a pip-installable Python packages with a `setup.py`. This would allow to include `pds-tools` as an installable package in my `setup.py` and, in general, in the `requirements.txt` for external use.

Do you have any plan to make `pds-tools` as a pip-installable Python package?

**Comment by dmopalmer** [comment]
I needed a vicar reader, and rather than just copying the vicar.py file to one of my libraries, I rabbit-holed into making it pip installable.  (Moving files into a directory, adding __init__.py, adding setup.py, and doing a quick half-way convert to python3).  It is checked into my fork of the project in the branch `pipable`, which I have made the default branch.

`https://github.com/dmopalmer/pds-tools`

@markshowalter if making this code pip-installable fits into your plans, this is a good starting point.

I have tested nothing but the vicar reader.

To install:

```
pip install git+https://github.com/dmopalmer/pds-tools.git@pipable
```

To use:
```
import pdstools
import numpy as np
import matplotlib.pyplot as plt

f = '/private/tmp/C2696649_RAW.IMG'

vicimage = pdstools.VicarImage.from_file(f)
print(vicimage.as_dict())
a = vicimage.get_2d_array()
plt.imshow(a, cmap='gray', vmin=24, vmax=34)
```

**Comment by rfrenchseti** [comment]
@dmopalmer I'm glad you found our software useful and we're grateful you were willing to spend the time to make it pip-installable. This is definitely something that we need to formally do soon! We'll make good use of your branch in the process. Thanks for your contribution.

**Comment by rfrenchseti** [comment]
We will be converting each relevant module in pds-tools into its own pip-installable package on PyPI. The name of the package will be `pdsrms_<module>` and will install `<module>`. For example, `pip install pdsrms_gravity` will install `gravity`. GitHub actions will be used to package the modules and upload them to PyPI. The modules that have unit tests will be run automatically (including code coverage) through GitHub actions and appropriate badges added to the README,

starcat: ignore (I will move this elsewhere)

gravity.py: has unit tests

interval.py: ignore (deprecated)

julian.py: has unit tests
julian_dateparser.py

pdsparser.py

pdstable.py: has unit tests

picmaker.py
colornames.py

solar.py

tabulation.py: has unit tests

textkernel.py: has unit tests

tiff16.py: has unit tests

vax.py: has unit tests

vicar.py

**Comment by rfrenchseti** [comment]
This has been done by breaking out each module into its own repo
